drop table EXERCISE_CATEGORY cascade constraints;

create table EXERCISE_CATEGORY (
  category_id number generated by default on null as identity,
  name varchar2(100) not null,
  constraint pk_exercise_category primary key (category_id),
  constraint uq_exercise_category_name unique (name)
);

exit;
