drop table WORKOUT_ENTRY cascade constraints;

create table WORKOUT_ENTRY (
  entry_id number generated by default on null as identity,
  log_id number not null,
  exercise_id number not null,
  value number,
  sets number,
  notes varchar2(1000),
  constraint pk_workout_entry primary key (entry_id),
  constraint fk_workout_entry_log foreign key (log_id) references WORKOUT_LOG(log_id),
  constraint fk_workout_entry_exercise foreign key (exercise_id) references EXERCISE(exercise_id)
);

exit;
