drop table WORKOUT_LOG cascade constraints;

create table WORKOUT_LOG (
  log_id number generated by default on null as identity,
  user_id number not null,
  log_date date default sysdate not null,
  is_private number(1) default 0 not null,
  title varchar2(100) not null,
  description varchar2(1000),
  hype_count number,
  comment_count number,
  notes varchar2(2000),
  created_at timestamp default current_timestamp not null,
  constraint pk_workout_log primary key (log_id),
  constraint fk_workout_log_user foreign key (user_id) references USERS(user_id),
  constraint ck_workout_log_is_private check (is_private in (0, 1))
);

exit;
