drop table AVATAR_ITEM cascade constraints;

create table AVATAR_ITEM (
  item_id number generated by default on null as identity,
  name varchar2(150) not null,
  item_type varchar2(50) not null,
  unlock_condition varchar2(500),
  xp_required number default 0 not null,
  image_url varchar2(500),
  constraint pk_avatar_item primary key (item_id),
  constraint ck_avatar_item_xp_required check (xp_required >= 0)
);

exit;
