drop table CHALLENGE cascade constraints;

create table CHALLENGE (
  challenge_id number generated by default on null as identity,
  creator_id number not null,
  exercise_id number not null,
  title varchar2(200) not null,
  description varchar2(2000),
  target_value number not null,
  start_date date not null,
  end_date date not null,
  is_public number(1) default 1 not null,
  created_at timestamp default current_timestamp not null,
  constraint pk_challenge primary key (challenge_id),
  constraint fk_challenge_creator foreign key (creator_id) references USERS(user_id),
  constraint fk_challenge_exercise foreign key (exercise_id) references EXERCISE(exercise_id),
  constraint ck_challenge_is_public check (is_public in (0, 1)),
  constraint ck_challenge_dates check (end_date >= start_date)
);

exit;
