drop table EXERCISE cascade constraints;

create table EXERCISE (
  exercise_id number generated by default on null as identity,
  category_id number not null,
  name varchar2(150) not null,
  description varchar2(1000),
  constraint pk_exercise primary key (exercise_id),
  constraint fk_exercise_category foreign key (category_id) references EXERCISE_CATEGORY(category_id)
);

exit;
