drop table GOAL cascade constraints;

create table GOAL (
  goal_id number generated by default on null as identity,
  user_id number not null,
  exercise_id number not null,
  title varchar2(200) not null,
  target_value number not null,
  deadline date,
  created_at timestamp default current_timestamp not null,
  constraint pk_goal primary key (goal_id),
  constraint fk_goal_user foreign key (user_id) references USERS(user_id),
  constraint fk_goal_exercise foreign key (exercise_id) references EXERCISE(exercise_id)
);

exit;
