drop table FEED_COMMENT cascade constraints;

create table FEED_COMMENT (
  comment_id number generated by default on null as identity,
  log_id number not null,
  user_id number not null,
  comment_text varchar2(1000) not null,
  created_at timestamp default current_timestamp not null,
  constraint pk_feed_comment primary key (comment_id),
  constraint fk_feed_comment_log foreign key (log_id) references WORKOUT_LOG(log_id),
  constraint fk_feed_comment_user foreign key (user_id) references USERS(user_id)
);

exit;
