drop table AVATAR cascade constraints;

create table AVATAR (
  avatar_id number generated by default on null as identity,
  user_id number not null,
  avatar_level number default 1 not null,
  xp number default 0 not null,
  constraint pk_avatar primary key (avatar_id),
  constraint uq_avatar_user unique (user_id),
  constraint fk_avatar_user foreign key (user_id) references USERS(user_id),
  constraint ck_avatar_level check (avatar_level >= 1),
  constraint ck_avatar_xp check (xp >= 0)
);

exit;
